### ISSUE TITLE
Sort lists alphabetically

### ISSUE THREAD

**Issue by eliperelman** [reyronald/awesome-toolkits#3]
In order to make lists fair, I think sorting alphabetically would be nice. 😃

**Comment by reyronald** [comment]
Hehe, yeah, I didn't order it alphabetically because I thought it would be more beneficial to the consumer of the list to have related resources grouped together, and have the most common ones on top. After all, these toolkits are often used by beginners which might not have the context that we do as experienced devs.

Also, I don't think these projects are competing against each other, they all have their own use case. @gaearon even included some thoughts on this matter here: https://github.com/facebookincubator/create-react-app#popular-alternatives

However I'm still open to sorting the list any other way! Is anybody else reading this and want to comment?

**Comment by eliperelman** [comment]
I meant ordering each section alphabetically.
