### ISSUE TITLE
Technicality about CRA

### ISSUE THREAD

**Issue by gillchristian** [reyronald/awesome-toolkits#7]
_As the title says, this is a technicality so take it as that and if you don't agree just close the issue_. :sweat_smile: 

Create React App is a bootstrap tool or generator. The real toolkit is the `react-scripts` package. What CRA does is create a project with `react`, `react-dom` and `react-scripts` installed and some starter files.

My suggestion is to change `react-scripts` description or put it as part of CRA description or put it in the web list together with CRA.

Maybe @gaearon has a suggestion. _If he ever reads this_ :sweat_smile:

What do you think ?

**Comment by gaearon** [comment]
I don't feel strongly. If it had to be deduplicated then I'd prefer something like

* react-scripts (part of Create React App) — ...

so that it’s obvious CRA is a real toolkit and not a boilerplate generator.

The brand name is CRA though so we can't "lose" that completely either.

**Comment by reyronald** [comment]
Yeah, to be honest at first I wasn't even very convinced to add `react-scripts` as an entry of its own, since like @gaearon said, the "brand" is actually CRA, and that's the tool the user sees is creating his/her app. But I saw value in having it regardless because that's where all the magic and power happens, and can serve as inspiration for other people trying to build their own toolkits for their use cases.

@gillchristian @gaearon What would you change the description to? I tried to make it clear that it was related to CRA, but it could be improved of course. Also, I didn't know if it belonged to the Web section so I just threw it in Other without thinking about it too much, that could change too.

**Comment by gaearon** [comment]
I'm happy with how it is but don't feel strongly about changing it

**Comment by gillchristian** [comment]
As I said this is a technicality so lets leave it as is. 😄 

Thanks Dan for sharing your opinions!
